### ISSUE TITLE
Param strings are not escaped

### ISSUE THREAD

**Issue by dnsmkl** [k0kubun/graphql-query-builder#1]
I was checking out your library and noticed issue that string content is not escaped.
(writing this just for info; I'm not actually using this lib)

Using ` compile 'com.github.k0kubun:graphql-query-builder:0.2.0'`

    public void checkGraphql2() {
        Map<String, Object> params = new HashMap<>();
        params.put("articleTest", "contains\"quote");

        final GraphQLObject requestedFields = createObjectBuilder().field("numberOfPages").build();
        String query = createQueryBuilder().object("Article", params, requestedFields).build();
        System.out.println("query: " + query);
    }

Actual result:

    query: Article(articleTest:"contains"quote") {
        numberOfPages
    }

Expected result:

    query: Article(articleTest:"contains\"quote") {
        numberOfPages
    }

**Comment by EriRan** [comment]
Hey, not sure how active this repo is but that is normal Java behavior. The input would need to contain two more escape chars to include the escape char so `"contains\\\"quote"`. Since we are building the query String in Java side and not as a piece of graphQL text, I'd say its better to play by Java's rules.

**Comment by k0kubun** [comment]
I think now it generates `"contains\\\"quote"`.
